CREATE TABLE UTILISATEUR(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(30) NOT NULL,
  password VARCHAR(60) NOT NULL
);
INSERT INTO UTILISATEUR(login, password) VALUES ("test", PASSWORD('test'));

CREATE TABLE TAG(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tag VARCHAR(50) NOT NULL
);
